package com.ronyao.cca.db.model;

import java.math.BigDecimal;

public class AnnualOutput {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column annual_output.id
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	private Byte id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column annual_output.voltageRankId
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	private Integer voltagerankid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column annual_output.projectType
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	private Byte projecttype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column annual_output.timeLimit
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	private Byte timelimit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column annual_output.projectNum
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	private BigDecimal projectnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column annual_output.annualOutPut
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	private Integer annualoutput;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column annual_output.remark
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column annual_output.createTime
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	private String createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column annual_output.updateTime
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	private String updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column annual_output.id
	 * @return  the value of annual_output.id
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	public Byte getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column annual_output.id
	 * @param id  the value for annual_output.id
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	public void setId(Byte id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column annual_output.voltageRankId
	 * @return  the value of annual_output.voltageRankId
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	public Integer getVoltagerankid() {
		return voltagerankid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column annual_output.voltageRankId
	 * @param voltagerankid  the value for annual_output.voltageRankId
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	public void setVoltagerankid(Integer voltagerankid) {
		this.voltagerankid = voltagerankid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column annual_output.projectType
	 * @return  the value of annual_output.projectType
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	public Byte getProjecttype() {
		return projecttype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column annual_output.projectType
	 * @param projecttype  the value for annual_output.projectType
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	public void setProjecttype(Byte projecttype) {
		this.projecttype = projecttype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column annual_output.timeLimit
	 * @return  the value of annual_output.timeLimit
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	public Byte getTimelimit() {
		return timelimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column annual_output.timeLimit
	 * @param timelimit  the value for annual_output.timeLimit
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	public void setTimelimit(Byte timelimit) {
		this.timelimit = timelimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column annual_output.projectNum
	 * @return  the value of annual_output.projectNum
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	public BigDecimal getProjectnum() {
		return projectnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column annual_output.projectNum
	 * @param projectnum  the value for annual_output.projectNum
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	public void setProjectnum(BigDecimal projectnum) {
		this.projectnum = projectnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column annual_output.annualOutPut
	 * @return  the value of annual_output.annualOutPut
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	public Integer getAnnualoutput() {
		return annualoutput;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column annual_output.annualOutPut
	 * @param annualoutput  the value for annual_output.annualOutPut
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	public void setAnnualoutput(Integer annualoutput) {
		this.annualoutput = annualoutput;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column annual_output.remark
	 * @return  the value of annual_output.remark
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column annual_output.remark
	 * @param remark  the value for annual_output.remark
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column annual_output.createTime
	 * @return  the value of annual_output.createTime
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	public String getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column annual_output.createTime
	 * @param createtime  the value for annual_output.createTime
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime == null ? null : createtime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column annual_output.updateTime
	 * @return  the value of annual_output.updateTime
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	public String getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column annual_output.updateTime
	 * @param updatetime  the value for annual_output.updateTime
	 * @mbggenerated  Tue Jan 12 13:43:05 CST 2016
	 */
	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime == null ? null : updatetime.trim();
	}
}