package com.ronyao.cca.db.model;

public class EnterprisePerson {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_person.id
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_person.enterpriseId
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	private Integer enterpriseid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_person.constructorOne
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	private Integer constructorone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_person.constructorTwo
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	private Integer constructortwo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_person.constructorTotal
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	private Integer constructortotal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_person.staffMiddle
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	private Integer staffmiddle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_person.staffHigh
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	private Integer staffhigh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_person.staffTotal
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	private Integer stafftotal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_person.skillMiddle
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	private Integer skillmiddle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_person.skillHigh
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	private Integer skillhigh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_person.skillTech
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	private Integer skilltech;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_person.skillTechHigh
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	private Integer skilltechhigh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_person.skillTotal
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	private Integer skilltotal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_person.createTime
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	private String createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_person.updateTime
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	private String updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_person.id
	 * @return  the value of enterprise_person.id
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_person.id
	 * @param id  the value for enterprise_person.id
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_person.enterpriseId
	 * @return  the value of enterprise_person.enterpriseId
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public Integer getEnterpriseid() {
		return enterpriseid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_person.enterpriseId
	 * @param enterpriseid  the value for enterprise_person.enterpriseId
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public void setEnterpriseid(Integer enterpriseid) {
		this.enterpriseid = enterpriseid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_person.constructorOne
	 * @return  the value of enterprise_person.constructorOne
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public Integer getConstructorone() {
		return constructorone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_person.constructorOne
	 * @param constructorone  the value for enterprise_person.constructorOne
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public void setConstructorone(Integer constructorone) {
		this.constructorone = constructorone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_person.constructorTwo
	 * @return  the value of enterprise_person.constructorTwo
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public Integer getConstructortwo() {
		return constructortwo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_person.constructorTwo
	 * @param constructortwo  the value for enterprise_person.constructorTwo
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public void setConstructortwo(Integer constructortwo) {
		this.constructortwo = constructortwo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_person.constructorTotal
	 * @return  the value of enterprise_person.constructorTotal
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public Integer getConstructortotal() {
		return constructortotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_person.constructorTotal
	 * @param constructortotal  the value for enterprise_person.constructorTotal
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public void setConstructortotal(Integer constructortotal) {
		this.constructortotal = constructortotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_person.staffMiddle
	 * @return  the value of enterprise_person.staffMiddle
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public Integer getStaffmiddle() {
		return staffmiddle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_person.staffMiddle
	 * @param staffmiddle  the value for enterprise_person.staffMiddle
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public void setStaffmiddle(Integer staffmiddle) {
		this.staffmiddle = staffmiddle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_person.staffHigh
	 * @return  the value of enterprise_person.staffHigh
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public Integer getStaffhigh() {
		return staffhigh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_person.staffHigh
	 * @param staffhigh  the value for enterprise_person.staffHigh
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public void setStaffhigh(Integer staffhigh) {
		this.staffhigh = staffhigh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_person.staffTotal
	 * @return  the value of enterprise_person.staffTotal
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public Integer getStafftotal() {
		return stafftotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_person.staffTotal
	 * @param stafftotal  the value for enterprise_person.staffTotal
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public void setStafftotal(Integer stafftotal) {
		this.stafftotal = stafftotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_person.skillMiddle
	 * @return  the value of enterprise_person.skillMiddle
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public Integer getSkillmiddle() {
		return skillmiddle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_person.skillMiddle
	 * @param skillmiddle  the value for enterprise_person.skillMiddle
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public void setSkillmiddle(Integer skillmiddle) {
		this.skillmiddle = skillmiddle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_person.skillHigh
	 * @return  the value of enterprise_person.skillHigh
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public Integer getSkillhigh() {
		return skillhigh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_person.skillHigh
	 * @param skillhigh  the value for enterprise_person.skillHigh
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public void setSkillhigh(Integer skillhigh) {
		this.skillhigh = skillhigh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_person.skillTech
	 * @return  the value of enterprise_person.skillTech
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public Integer getSkilltech() {
		return skilltech;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_person.skillTech
	 * @param skilltech  the value for enterprise_person.skillTech
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public void setSkilltech(Integer skilltech) {
		this.skilltech = skilltech;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_person.skillTechHigh
	 * @return  the value of enterprise_person.skillTechHigh
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public Integer getSkilltechhigh() {
		return skilltechhigh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_person.skillTechHigh
	 * @param skilltechhigh  the value for enterprise_person.skillTechHigh
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public void setSkilltechhigh(Integer skilltechhigh) {
		this.skilltechhigh = skilltechhigh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_person.skillTotal
	 * @return  the value of enterprise_person.skillTotal
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public Integer getSkilltotal() {
		return skilltotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_person.skillTotal
	 * @param skilltotal  the value for enterprise_person.skillTotal
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public void setSkilltotal(Integer skilltotal) {
		this.skilltotal = skilltotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_person.createTime
	 * @return  the value of enterprise_person.createTime
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public String getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_person.createTime
	 * @param createtime  the value for enterprise_person.createTime
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime == null ? null : createtime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_person.updateTime
	 * @return  the value of enterprise_person.updateTime
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public String getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_person.updateTime
	 * @param updatetime  the value for enterprise_person.updateTime
	 * @mbggenerated  Tue Dec 22 10:55:38 CST 2015
	 */
	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime == null ? null : updatetime.trim();
	}
}