package com.ronyao.cca.db.model;

public class EnterprisePerManage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_per_manage.id
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_per_manage.enterpriseId
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	private Integer enterpriseid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_per_manage.professionType
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	private Integer professiontype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_per_manage.oneManager
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	private Integer onemanager;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_per_manage.twoManager
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	private Integer twomanager;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_per_manage.oneChief
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	private Integer onechief;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_per_manage.twoChief
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	private Integer twochief;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_per_manage.safetyOfficer
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	private Integer safetyofficer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_per_manage.inspector
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	private Integer inspector;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_per_manage.technician
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	private Integer technician;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_per_manage.costMember
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	private Integer costmember;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_per_manage.documenter
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	private Integer documenter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_per_manage.integrator
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	private Integer integrator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_per_manage.material
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	private Integer material;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_per_manage.expeditor
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	private Integer expeditor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_per_manage.constructionTeam
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	private Integer constructionteam;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_per_manage.plurality
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	private Integer plurality;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_per_manage.sum
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	private Integer sum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_per_manage.createTime
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	private String createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_per_manage.updateTime
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	private String updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_per_manage.id
	 * @return  the value of enterprise_per_manage.id
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_per_manage.id
	 * @param id  the value for enterprise_per_manage.id
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_per_manage.enterpriseId
	 * @return  the value of enterprise_per_manage.enterpriseId
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public Integer getEnterpriseid() {
		return enterpriseid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_per_manage.enterpriseId
	 * @param enterpriseid  the value for enterprise_per_manage.enterpriseId
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setEnterpriseid(Integer enterpriseid) {
		this.enterpriseid = enterpriseid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_per_manage.professionType
	 * @return  the value of enterprise_per_manage.professionType
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public Integer getProfessiontype() {
		return professiontype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_per_manage.professionType
	 * @param professiontype  the value for enterprise_per_manage.professionType
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setProfessiontype(Integer professiontype) {
		this.professiontype = professiontype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_per_manage.oneManager
	 * @return  the value of enterprise_per_manage.oneManager
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public Integer getOnemanager() {
		return onemanager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_per_manage.oneManager
	 * @param onemanager  the value for enterprise_per_manage.oneManager
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setOnemanager(Integer onemanager) {
		this.onemanager = onemanager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_per_manage.twoManager
	 * @return  the value of enterprise_per_manage.twoManager
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public Integer getTwomanager() {
		return twomanager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_per_manage.twoManager
	 * @param twomanager  the value for enterprise_per_manage.twoManager
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setTwomanager(Integer twomanager) {
		this.twomanager = twomanager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_per_manage.oneChief
	 * @return  the value of enterprise_per_manage.oneChief
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public Integer getOnechief() {
		return onechief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_per_manage.oneChief
	 * @param onechief  the value for enterprise_per_manage.oneChief
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setOnechief(Integer onechief) {
		this.onechief = onechief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_per_manage.twoChief
	 * @return  the value of enterprise_per_manage.twoChief
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public Integer getTwochief() {
		return twochief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_per_manage.twoChief
	 * @param twochief  the value for enterprise_per_manage.twoChief
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setTwochief(Integer twochief) {
		this.twochief = twochief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_per_manage.safetyOfficer
	 * @return  the value of enterprise_per_manage.safetyOfficer
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public Integer getSafetyofficer() {
		return safetyofficer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_per_manage.safetyOfficer
	 * @param safetyofficer  the value for enterprise_per_manage.safetyOfficer
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setSafetyofficer(Integer safetyofficer) {
		this.safetyofficer = safetyofficer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_per_manage.inspector
	 * @return  the value of enterprise_per_manage.inspector
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public Integer getInspector() {
		return inspector;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_per_manage.inspector
	 * @param inspector  the value for enterprise_per_manage.inspector
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setInspector(Integer inspector) {
		this.inspector = inspector;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_per_manage.technician
	 * @return  the value of enterprise_per_manage.technician
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public Integer getTechnician() {
		return technician;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_per_manage.technician
	 * @param technician  the value for enterprise_per_manage.technician
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setTechnician(Integer technician) {
		this.technician = technician;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_per_manage.costMember
	 * @return  the value of enterprise_per_manage.costMember
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public Integer getCostmember() {
		return costmember;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_per_manage.costMember
	 * @param costmember  the value for enterprise_per_manage.costMember
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setCostmember(Integer costmember) {
		this.costmember = costmember;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_per_manage.documenter
	 * @return  the value of enterprise_per_manage.documenter
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public Integer getDocumenter() {
		return documenter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_per_manage.documenter
	 * @param documenter  the value for enterprise_per_manage.documenter
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setDocumenter(Integer documenter) {
		this.documenter = documenter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_per_manage.integrator
	 * @return  the value of enterprise_per_manage.integrator
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public Integer getIntegrator() {
		return integrator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_per_manage.integrator
	 * @param integrator  the value for enterprise_per_manage.integrator
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setIntegrator(Integer integrator) {
		this.integrator = integrator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_per_manage.material
	 * @return  the value of enterprise_per_manage.material
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public Integer getMaterial() {
		return material;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_per_manage.material
	 * @param material  the value for enterprise_per_manage.material
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setMaterial(Integer material) {
		this.material = material;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_per_manage.expeditor
	 * @return  the value of enterprise_per_manage.expeditor
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public Integer getExpeditor() {
		return expeditor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_per_manage.expeditor
	 * @param expeditor  the value for enterprise_per_manage.expeditor
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setExpeditor(Integer expeditor) {
		this.expeditor = expeditor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_per_manage.constructionTeam
	 * @return  the value of enterprise_per_manage.constructionTeam
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public Integer getConstructionteam() {
		return constructionteam;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_per_manage.constructionTeam
	 * @param constructionteam  the value for enterprise_per_manage.constructionTeam
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setConstructionteam(Integer constructionteam) {
		this.constructionteam = constructionteam;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_per_manage.plurality
	 * @return  the value of enterprise_per_manage.plurality
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public Integer getPlurality() {
		return plurality;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_per_manage.plurality
	 * @param plurality  the value for enterprise_per_manage.plurality
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setPlurality(Integer plurality) {
		this.plurality = plurality;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_per_manage.sum
	 * @return  the value of enterprise_per_manage.sum
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public Integer getSum() {
		return sum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_per_manage.sum
	 * @param sum  the value for enterprise_per_manage.sum
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setSum(Integer sum) {
		this.sum = sum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_per_manage.createTime
	 * @return  the value of enterprise_per_manage.createTime
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public String getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_per_manage.createTime
	 * @param createtime  the value for enterprise_per_manage.createTime
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime == null ? null : createtime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_per_manage.updateTime
	 * @return  the value of enterprise_per_manage.updateTime
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public String getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_per_manage.updateTime
	 * @param updatetime  the value for enterprise_per_manage.updateTime
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime == null ? null : updatetime.trim();
	}
}