package com.ronyao.cca.db.model;

public class EnterpriseFile {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_file.id
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_file.enterpriseId
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	private Integer enterpriseid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_file.fileType
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	private Byte filetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_file.aptitudeRankId
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	private Byte aptituderankid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_file.aptitudeId
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	private Byte aptitudeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_file.path
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	private String path;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_file.createTime
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	private String createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_file.updateTime
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	private String updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_file.id
	 * @return  the value of enterprise_file.id
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_file.id
	 * @param id  the value for enterprise_file.id
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_file.enterpriseId
	 * @return  the value of enterprise_file.enterpriseId
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	public Integer getEnterpriseid() {
		return enterpriseid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_file.enterpriseId
	 * @param enterpriseid  the value for enterprise_file.enterpriseId
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	public void setEnterpriseid(Integer enterpriseid) {
		this.enterpriseid = enterpriseid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_file.fileType
	 * @return  the value of enterprise_file.fileType
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	public Byte getFiletype() {
		return filetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_file.fileType
	 * @param filetype  the value for enterprise_file.fileType
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	public void setFiletype(Byte filetype) {
		this.filetype = filetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_file.aptitudeRankId
	 * @return  the value of enterprise_file.aptitudeRankId
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	public Byte getAptituderankid() {
		return aptituderankid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_file.aptitudeRankId
	 * @param aptituderankid  the value for enterprise_file.aptitudeRankId
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	public void setAptituderankid(Byte aptituderankid) {
		this.aptituderankid = aptituderankid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_file.aptitudeId
	 * @return  the value of enterprise_file.aptitudeId
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	public Byte getAptitudeid() {
		return aptitudeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_file.aptitudeId
	 * @param aptitudeid  the value for enterprise_file.aptitudeId
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	public void setAptitudeid(Byte aptitudeid) {
		this.aptitudeid = aptitudeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_file.path
	 * @return  the value of enterprise_file.path
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_file.path
	 * @param path  the value for enterprise_file.path
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	public void setPath(String path) {
		this.path = path == null ? null : path.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_file.createTime
	 * @return  the value of enterprise_file.createTime
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	public String getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_file.createTime
	 * @param createtime  the value for enterprise_file.createTime
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime == null ? null : createtime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_file.updateTime
	 * @return  the value of enterprise_file.updateTime
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	public String getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_file.updateTime
	 * @param updatetime  the value for enterprise_file.updateTime
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime == null ? null : updatetime.trim();
	}
}