package com.ronyao.cca.db.model;

public class EnterpriseAptitude {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_aptitude.id
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_aptitude.aptitudeId
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	private Byte aptitudeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_aptitude.aptitudeRank
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	private Byte aptituderank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_aptitude.qualifications
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	private String qualifications;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_aptitude.practicing
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	private String practicing;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_aptitude.charge
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	private String charge;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_aptitude.technical
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	private String technical;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_aptitude.skills
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	private String skills;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_aptitude.jobRange
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	private String jobrange;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_aptitude.createTime
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	private String createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_aptitude.updateTime
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	private String updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_aptitude.id
	 * @return  the value of enterprise_aptitude.id
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_aptitude.id
	 * @param id  the value for enterprise_aptitude.id
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_aptitude.aptitudeId
	 * @return  the value of enterprise_aptitude.aptitudeId
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public Byte getAptitudeid() {
		return aptitudeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_aptitude.aptitudeId
	 * @param aptitudeid  the value for enterprise_aptitude.aptitudeId
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public void setAptitudeid(Byte aptitudeid) {
		this.aptitudeid = aptitudeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_aptitude.aptitudeRank
	 * @return  the value of enterprise_aptitude.aptitudeRank
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public Byte getAptituderank() {
		return aptituderank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_aptitude.aptitudeRank
	 * @param aptituderank  the value for enterprise_aptitude.aptitudeRank
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public void setAptituderank(Byte aptituderank) {
		this.aptituderank = aptituderank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_aptitude.qualifications
	 * @return  the value of enterprise_aptitude.qualifications
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public String getQualifications() {
		return qualifications;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_aptitude.qualifications
	 * @param qualifications  the value for enterprise_aptitude.qualifications
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public void setQualifications(String qualifications) {
		this.qualifications = qualifications == null ? null : qualifications
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_aptitude.practicing
	 * @return  the value of enterprise_aptitude.practicing
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public String getPracticing() {
		return practicing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_aptitude.practicing
	 * @param practicing  the value for enterprise_aptitude.practicing
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public void setPracticing(String practicing) {
		this.practicing = practicing == null ? null : practicing.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_aptitude.charge
	 * @return  the value of enterprise_aptitude.charge
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public String getCharge() {
		return charge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_aptitude.charge
	 * @param charge  the value for enterprise_aptitude.charge
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public void setCharge(String charge) {
		this.charge = charge == null ? null : charge.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_aptitude.technical
	 * @return  the value of enterprise_aptitude.technical
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public String getTechnical() {
		return technical;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_aptitude.technical
	 * @param technical  the value for enterprise_aptitude.technical
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public void setTechnical(String technical) {
		this.technical = technical == null ? null : technical.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_aptitude.skills
	 * @return  the value of enterprise_aptitude.skills
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public String getSkills() {
		return skills;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_aptitude.skills
	 * @param skills  the value for enterprise_aptitude.skills
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public void setSkills(String skills) {
		this.skills = skills == null ? null : skills.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_aptitude.jobRange
	 * @return  the value of enterprise_aptitude.jobRange
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public String getJobrange() {
		return jobrange;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_aptitude.jobRange
	 * @param jobrange  the value for enterprise_aptitude.jobRange
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public void setJobrange(String jobrange) {
		this.jobrange = jobrange == null ? null : jobrange.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_aptitude.createTime
	 * @return  the value of enterprise_aptitude.createTime
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public String getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_aptitude.createTime
	 * @param createtime  the value for enterprise_aptitude.createTime
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime == null ? null : createtime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_aptitude.updateTime
	 * @return  the value of enterprise_aptitude.updateTime
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public String getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_aptitude.updateTime
	 * @param updatetime  the value for enterprise_aptitude.updateTime
	 * @mbggenerated  Wed Dec 16 10:35:10 CST 2015
	 */
	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime == null ? null : updatetime.trim();
	}
}