package com.ronyao.cca.db.model;

public class EquipmentBear {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment_bear.id
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment_bear.name
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment_bear.voltageRankId
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	private Byte voltagerankid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment_bear.lineType
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	private Byte linetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment_bear.linePlain
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	private Byte lineplain;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment_bear.lineBrae
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	private Byte linebrae;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment_bear.explains
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	private String explains;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment_bear.createTime
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	private String createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment_bear.updateTime
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	private String updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment_bear.id
	 * @return  the value of equipment_bear.id
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment_bear.id
	 * @param id  the value for equipment_bear.id
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment_bear.name
	 * @return  the value of equipment_bear.name
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment_bear.name
	 * @param name  the value for equipment_bear.name
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment_bear.voltageRankId
	 * @return  the value of equipment_bear.voltageRankId
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	public Byte getVoltagerankid() {
		return voltagerankid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment_bear.voltageRankId
	 * @param voltagerankid  the value for equipment_bear.voltageRankId
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	public void setVoltagerankid(Byte voltagerankid) {
		this.voltagerankid = voltagerankid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment_bear.lineType
	 * @return  the value of equipment_bear.lineType
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	public Byte getLinetype() {
		return linetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment_bear.lineType
	 * @param linetype  the value for equipment_bear.lineType
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	public void setLinetype(Byte linetype) {
		this.linetype = linetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment_bear.linePlain
	 * @return  the value of equipment_bear.linePlain
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	public Byte getLineplain() {
		return lineplain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment_bear.linePlain
	 * @param lineplain  the value for equipment_bear.linePlain
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	public void setLineplain(Byte lineplain) {
		this.lineplain = lineplain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment_bear.lineBrae
	 * @return  the value of equipment_bear.lineBrae
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	public Byte getLinebrae() {
		return linebrae;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment_bear.lineBrae
	 * @param linebrae  the value for equipment_bear.lineBrae
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	public void setLinebrae(Byte linebrae) {
		this.linebrae = linebrae;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment_bear.explains
	 * @return  the value of equipment_bear.explains
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	public String getExplains() {
		return explains;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment_bear.explains
	 * @param explains  the value for equipment_bear.explains
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	public void setExplains(String explains) {
		this.explains = explains == null ? null : explains.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment_bear.createTime
	 * @return  the value of equipment_bear.createTime
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	public String getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment_bear.createTime
	 * @param createtime  the value for equipment_bear.createTime
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime == null ? null : createtime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment_bear.updateTime
	 * @return  the value of equipment_bear.updateTime
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	public String getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment_bear.updateTime
	 * @param updatetime  the value for equipment_bear.updateTime
	 * @mbggenerated  Fri Dec 11 13:17:30 CST 2015
	 */
	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime == null ? null : updatetime.trim();
	}
}