package com.ronyao.cca.db.model;

public class ProjectBuild {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_build.id
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_build.supervisorUnit
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	private String supervisorunit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_build.enterpriseId
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	private Integer enterpriseid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_build.year
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	private Integer year;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_build.classify
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	private Integer classify;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_build.line110kv
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	private Integer line110kv;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_build.line220kv
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	private Integer line220kv;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_build.line500kv
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	private Integer line500kv;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_build.power110kv
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	private Integer power110kv;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_build.power220kv
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	private Integer power220kv;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_build.power500kv
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	private Integer power500kv;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_build.createTime
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	private String createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project_build.updateTime
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	private String updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_build.id
	 * @return  the value of project_build.id
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_build.id
	 * @param id  the value for project_build.id
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_build.supervisorUnit
	 * @return  the value of project_build.supervisorUnit
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public String getSupervisorunit() {
		return supervisorunit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_build.supervisorUnit
	 * @param supervisorunit  the value for project_build.supervisorUnit
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public void setSupervisorunit(String supervisorunit) {
		this.supervisorunit = supervisorunit == null ? null : supervisorunit
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_build.enterpriseId
	 * @return  the value of project_build.enterpriseId
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public Integer getEnterpriseid() {
		return enterpriseid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_build.enterpriseId
	 * @param enterpriseid  the value for project_build.enterpriseId
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public void setEnterpriseid(Integer enterpriseid) {
		this.enterpriseid = enterpriseid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_build.year
	 * @return  the value of project_build.year
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public Integer getYear() {
		return year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_build.year
	 * @param year  the value for project_build.year
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public void setYear(Integer year) {
		this.year = year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_build.classify
	 * @return  the value of project_build.classify
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public Integer getClassify() {
		return classify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_build.classify
	 * @param classify  the value for project_build.classify
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public void setClassify(Integer classify) {
		this.classify = classify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_build.line110kv
	 * @return  the value of project_build.line110kv
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public Integer getLine110kv() {
		return line110kv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_build.line110kv
	 * @param line110kv  the value for project_build.line110kv
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public void setLine110kv(Integer line110kv) {
		this.line110kv = line110kv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_build.line220kv
	 * @return  the value of project_build.line220kv
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public Integer getLine220kv() {
		return line220kv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_build.line220kv
	 * @param line220kv  the value for project_build.line220kv
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public void setLine220kv(Integer line220kv) {
		this.line220kv = line220kv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_build.line500kv
	 * @return  the value of project_build.line500kv
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public Integer getLine500kv() {
		return line500kv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_build.line500kv
	 * @param line500kv  the value for project_build.line500kv
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public void setLine500kv(Integer line500kv) {
		this.line500kv = line500kv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_build.power110kv
	 * @return  the value of project_build.power110kv
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public Integer getPower110kv() {
		return power110kv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_build.power110kv
	 * @param power110kv  the value for project_build.power110kv
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public void setPower110kv(Integer power110kv) {
		this.power110kv = power110kv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_build.power220kv
	 * @return  the value of project_build.power220kv
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public Integer getPower220kv() {
		return power220kv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_build.power220kv
	 * @param power220kv  the value for project_build.power220kv
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public void setPower220kv(Integer power220kv) {
		this.power220kv = power220kv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_build.power500kv
	 * @return  the value of project_build.power500kv
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public Integer getPower500kv() {
		return power500kv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_build.power500kv
	 * @param power500kv  the value for project_build.power500kv
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public void setPower500kv(Integer power500kv) {
		this.power500kv = power500kv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_build.createTime
	 * @return  the value of project_build.createTime
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public String getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_build.createTime
	 * @param createtime  the value for project_build.createTime
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime == null ? null : createtime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project_build.updateTime
	 * @return  the value of project_build.updateTime
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public String getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project_build.updateTime
	 * @param updatetime  the value for project_build.updateTime
	 * @mbggenerated  Mon Dec 21 11:37:23 CST 2015
	 */
	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime == null ? null : updatetime.trim();
	}
}