package com.ronyao.cca.db.model;

public class UserRoleLinkKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role_link.userId
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role_link.roleId
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	private Integer roleid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role_link.userId
	 * @return  the value of user_role_link.userId
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role_link.userId
	 * @param userid  the value for user_role_link.userId
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role_link.roleId
	 * @return  the value of user_role_link.roleId
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	public Integer getRoleid() {
		return roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role_link.roleId
	 * @param roleid  the value for user_role_link.roleId
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}
}