package com.ronyao.cca.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserLogExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_log
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_log
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_log
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_log
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public UserLogExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_log
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_log
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_log
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_log
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_log
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_log
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_log
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_log
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_log
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_log
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_log
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUidIsNull() {
			addCriterion("uid is null");
			return (Criteria) this;
		}

		public Criteria andUidIsNotNull() {
			addCriterion("uid is not null");
			return (Criteria) this;
		}

		public Criteria andUidEqualTo(Integer value) {
			addCriterion("uid =", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotEqualTo(Integer value) {
			addCriterion("uid <>", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThan(Integer value) {
			addCriterion("uid >", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThanOrEqualTo(Integer value) {
			addCriterion("uid >=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThan(Integer value) {
			addCriterion("uid <", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThanOrEqualTo(Integer value) {
			addCriterion("uid <=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidIn(List<Integer> values) {
			addCriterion("uid in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotIn(List<Integer> values) {
			addCriterion("uid not in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidBetween(Integer value1, Integer value2) {
			addCriterion("uid between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotBetween(Integer value1, Integer value2) {
			addCriterion("uid not between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andUserActionIsNull() {
			addCriterion("user_action is null");
			return (Criteria) this;
		}

		public Criteria andUserActionIsNotNull() {
			addCriterion("user_action is not null");
			return (Criteria) this;
		}

		public Criteria andUserActionEqualTo(String value) {
			addCriterion("user_action =", value, "userAction");
			return (Criteria) this;
		}

		public Criteria andUserActionNotEqualTo(String value) {
			addCriterion("user_action <>", value, "userAction");
			return (Criteria) this;
		}

		public Criteria andUserActionGreaterThan(String value) {
			addCriterion("user_action >", value, "userAction");
			return (Criteria) this;
		}

		public Criteria andUserActionGreaterThanOrEqualTo(String value) {
			addCriterion("user_action >=", value, "userAction");
			return (Criteria) this;
		}

		public Criteria andUserActionLessThan(String value) {
			addCriterion("user_action <", value, "userAction");
			return (Criteria) this;
		}

		public Criteria andUserActionLessThanOrEqualTo(String value) {
			addCriterion("user_action <=", value, "userAction");
			return (Criteria) this;
		}

		public Criteria andUserActionLike(String value) {
			addCriterion("user_action like", value, "userAction");
			return (Criteria) this;
		}

		public Criteria andUserActionNotLike(String value) {
			addCriterion("user_action not like", value, "userAction");
			return (Criteria) this;
		}

		public Criteria andUserActionIn(List<String> values) {
			addCriterion("user_action in", values, "userAction");
			return (Criteria) this;
		}

		public Criteria andUserActionNotIn(List<String> values) {
			addCriterion("user_action not in", values, "userAction");
			return (Criteria) this;
		}

		public Criteria andUserActionBetween(String value1, String value2) {
			addCriterion("user_action between", value1, value2, "userAction");
			return (Criteria) this;
		}

		public Criteria andUserActionNotBetween(String value1, String value2) {
			addCriterion("user_action not between", value1, value2,
					"userAction");
			return (Criteria) this;
		}

		public Criteria andOperateTimeIsNull() {
			addCriterion("operate_time is null");
			return (Criteria) this;
		}

		public Criteria andOperateTimeIsNotNull() {
			addCriterion("operate_time is not null");
			return (Criteria) this;
		}

		public Criteria andOperateTimeEqualTo(Date value) {
			addCriterion("operate_time =", value, "operateTime");
			return (Criteria) this;
		}

		public Criteria andOperateTimeNotEqualTo(Date value) {
			addCriterion("operate_time <>", value, "operateTime");
			return (Criteria) this;
		}

		public Criteria andOperateTimeGreaterThan(Date value) {
			addCriterion("operate_time >", value, "operateTime");
			return (Criteria) this;
		}

		public Criteria andOperateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("operate_time >=", value, "operateTime");
			return (Criteria) this;
		}

		public Criteria andOperateTimeLessThan(Date value) {
			addCriterion("operate_time <", value, "operateTime");
			return (Criteria) this;
		}

		public Criteria andOperateTimeLessThanOrEqualTo(Date value) {
			addCriterion("operate_time <=", value, "operateTime");
			return (Criteria) this;
		}

		public Criteria andOperateTimeIn(List<Date> values) {
			addCriterion("operate_time in", values, "operateTime");
			return (Criteria) this;
		}

		public Criteria andOperateTimeNotIn(List<Date> values) {
			addCriterion("operate_time not in", values, "operateTime");
			return (Criteria) this;
		}

		public Criteria andOperateTimeBetween(Date value1, Date value2) {
			addCriterion("operate_time between", value1, value2, "operateTime");
			return (Criteria) this;
		}

		public Criteria andOperateTimeNotBetween(Date value1, Date value2) {
			addCriterion("operate_time not between", value1, value2,
					"operateTime");
			return (Criteria) this;
		}

		public Criteria andIpAddressIsNull() {
			addCriterion("ip_address is null");
			return (Criteria) this;
		}

		public Criteria andIpAddressIsNotNull() {
			addCriterion("ip_address is not null");
			return (Criteria) this;
		}

		public Criteria andIpAddressEqualTo(String value) {
			addCriterion("ip_address =", value, "ipAddress");
			return (Criteria) this;
		}

		public Criteria andIpAddressNotEqualTo(String value) {
			addCriterion("ip_address <>", value, "ipAddress");
			return (Criteria) this;
		}

		public Criteria andIpAddressGreaterThan(String value) {
			addCriterion("ip_address >", value, "ipAddress");
			return (Criteria) this;
		}

		public Criteria andIpAddressGreaterThanOrEqualTo(String value) {
			addCriterion("ip_address >=", value, "ipAddress");
			return (Criteria) this;
		}

		public Criteria andIpAddressLessThan(String value) {
			addCriterion("ip_address <", value, "ipAddress");
			return (Criteria) this;
		}

		public Criteria andIpAddressLessThanOrEqualTo(String value) {
			addCriterion("ip_address <=", value, "ipAddress");
			return (Criteria) this;
		}

		public Criteria andIpAddressLike(String value) {
			addCriterion("ip_address like", value, "ipAddress");
			return (Criteria) this;
		}

		public Criteria andIpAddressNotLike(String value) {
			addCriterion("ip_address not like", value, "ipAddress");
			return (Criteria) this;
		}

		public Criteria andIpAddressIn(List<String> values) {
			addCriterion("ip_address in", values, "ipAddress");
			return (Criteria) this;
		}

		public Criteria andIpAddressNotIn(List<String> values) {
			addCriterion("ip_address not in", values, "ipAddress");
			return (Criteria) this;
		}

		public Criteria andIpAddressBetween(String value1, String value2) {
			addCriterion("ip_address between", value1, value2, "ipAddress");
			return (Criteria) this;
		}

		public Criteria andIpAddressNotBetween(String value1, String value2) {
			addCriterion("ip_address not between", value1, value2, "ipAddress");
			return (Criteria) this;
		}

		public Criteria andCommentInfoIsNull() {
			addCriterion("comment_info is null");
			return (Criteria) this;
		}

		public Criteria andCommentInfoIsNotNull() {
			addCriterion("comment_info is not null");
			return (Criteria) this;
		}

		public Criteria andCommentInfoEqualTo(String value) {
			addCriterion("comment_info =", value, "commentInfo");
			return (Criteria) this;
		}

		public Criteria andCommentInfoNotEqualTo(String value) {
			addCriterion("comment_info <>", value, "commentInfo");
			return (Criteria) this;
		}

		public Criteria andCommentInfoGreaterThan(String value) {
			addCriterion("comment_info >", value, "commentInfo");
			return (Criteria) this;
		}

		public Criteria andCommentInfoGreaterThanOrEqualTo(String value) {
			addCriterion("comment_info >=", value, "commentInfo");
			return (Criteria) this;
		}

		public Criteria andCommentInfoLessThan(String value) {
			addCriterion("comment_info <", value, "commentInfo");
			return (Criteria) this;
		}

		public Criteria andCommentInfoLessThanOrEqualTo(String value) {
			addCriterion("comment_info <=", value, "commentInfo");
			return (Criteria) this;
		}

		public Criteria andCommentInfoLike(String value) {
			addCriterion("comment_info like", value, "commentInfo");
			return (Criteria) this;
		}

		public Criteria andCommentInfoNotLike(String value) {
			addCriterion("comment_info not like", value, "commentInfo");
			return (Criteria) this;
		}

		public Criteria andCommentInfoIn(List<String> values) {
			addCriterion("comment_info in", values, "commentInfo");
			return (Criteria) this;
		}

		public Criteria andCommentInfoNotIn(List<String> values) {
			addCriterion("comment_info not in", values, "commentInfo");
			return (Criteria) this;
		}

		public Criteria andCommentInfoBetween(String value1, String value2) {
			addCriterion("comment_info between", value1, value2, "commentInfo");
			return (Criteria) this;
		}

		public Criteria andCommentInfoNotBetween(String value1, String value2) {
			addCriterion("comment_info not between", value1, value2,
					"commentInfo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_log
	 * @mbggenerated  Thu Dec 17 15:44:44 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_log
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 09 15:42:41 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}