package com.ronyao.cca.db.dao;

import com.ronyao.cca.db.model.EnterpriseAptitude;
import com.ronyao.cca.db.model.EnterpriseAptitudeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;
import com.ronyao.cca.db.model.EnterpriseAptitudeWithBLOBs;

public interface EnterpriseAptitudeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_aptitude
	 * @mbggenerated  Wed Jan 13 12:15:38 CST 2016
	 */
	@SelectProvider(type = EnterpriseAptitudeSqlProvider.class, method = "countByExample")
	int countByExample(EnterpriseAptitudeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_aptitude
	 * @mbggenerated  Wed Jan 13 12:15:38 CST 2016
	 */
	@DeleteProvider(type = EnterpriseAptitudeSqlProvider.class, method = "deleteByExample")
	int deleteByExample(EnterpriseAptitudeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_aptitude
	 * @mbggenerated  Wed Jan 13 12:15:38 CST 2016
	 */
	@Delete({ "delete from enterprise_aptitude",
			"where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_aptitude
	 * @mbggenerated  Wed Jan 13 12:15:38 CST 2016
	 */
	@Insert({
			"insert into enterprise_aptitude (aptitudeId, aptitudeRank, ",
			"qualifications, practicing, ",
			"createTime, updateTime, ",
			"charge, technical, ",
			"skills, jobRange)",
			"values (#{aptitudeid,jdbcType=TINYINT}, #{aptituderank,jdbcType=TINYINT}, ",
			"#{qualifications,jdbcType=VARCHAR}, #{practicing,jdbcType=VARCHAR}, ",
			"#{createtime,jdbcType=VARCHAR}, #{updatetime,jdbcType=VARCHAR}, ",
			"#{charge,jdbcType=LONGVARCHAR}, #{technical,jdbcType=LONGVARCHAR}, ",
			"#{skills,jdbcType=LONGVARCHAR}, #{jobrange,jdbcType=LONGVARCHAR})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
	int insert(EnterpriseAptitudeWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_aptitude
	 * @mbggenerated  Wed Jan 13 12:15:38 CST 2016
	 */
	@InsertProvider(type = EnterpriseAptitudeSqlProvider.class, method = "insertSelective")
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
	int insertSelective(EnterpriseAptitudeWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_aptitude
	 * @mbggenerated  Wed Jan 13 12:15:38 CST 2016
	 */
	@SelectProvider(type = EnterpriseAptitudeSqlProvider.class, method = "selectByExampleWithBLOBs")
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "aptitudeId", property = "aptitudeid", jdbcType = JdbcType.TINYINT),
			@Result(column = "aptitudeRank", property = "aptituderank", jdbcType = JdbcType.TINYINT),
			@Result(column = "qualifications", property = "qualifications", jdbcType = JdbcType.VARCHAR),
			@Result(column = "practicing", property = "practicing", jdbcType = JdbcType.VARCHAR),
			@Result(column = "createTime", property = "createtime", jdbcType = JdbcType.VARCHAR),
			@Result(column = "updateTime", property = "updatetime", jdbcType = JdbcType.VARCHAR),
			@Result(column = "charge", property = "charge", jdbcType = JdbcType.LONGVARCHAR),
			@Result(column = "technical", property = "technical", jdbcType = JdbcType.LONGVARCHAR),
			@Result(column = "skills", property = "skills", jdbcType = JdbcType.LONGVARCHAR),
			@Result(column = "jobRange", property = "jobrange", jdbcType = JdbcType.LONGVARCHAR) })
	List<EnterpriseAptitudeWithBLOBs> selectByExampleWithBLOBsWithRowbounds(
			EnterpriseAptitudeExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_aptitude
	 * @mbggenerated  Wed Jan 13 12:15:38 CST 2016
	 */
	@SelectProvider(type = EnterpriseAptitudeSqlProvider.class, method = "selectByExampleWithBLOBs")
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "aptitudeId", property = "aptitudeid", jdbcType = JdbcType.TINYINT),
			@Result(column = "aptitudeRank", property = "aptituderank", jdbcType = JdbcType.TINYINT),
			@Result(column = "qualifications", property = "qualifications", jdbcType = JdbcType.VARCHAR),
			@Result(column = "practicing", property = "practicing", jdbcType = JdbcType.VARCHAR),
			@Result(column = "createTime", property = "createtime", jdbcType = JdbcType.VARCHAR),
			@Result(column = "updateTime", property = "updatetime", jdbcType = JdbcType.VARCHAR),
			@Result(column = "charge", property = "charge", jdbcType = JdbcType.LONGVARCHAR),
			@Result(column = "technical", property = "technical", jdbcType = JdbcType.LONGVARCHAR),
			@Result(column = "skills", property = "skills", jdbcType = JdbcType.LONGVARCHAR),
			@Result(column = "jobRange", property = "jobrange", jdbcType = JdbcType.LONGVARCHAR) })
	List<EnterpriseAptitudeWithBLOBs> selectByExampleWithBLOBs(
			EnterpriseAptitudeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_aptitude
	 * @mbggenerated  Wed Jan 13 12:15:38 CST 2016
	 */
	@SelectProvider(type = EnterpriseAptitudeSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "aptitudeId", property = "aptitudeid", jdbcType = JdbcType.TINYINT),
			@Result(column = "aptitudeRank", property = "aptituderank", jdbcType = JdbcType.TINYINT),
			@Result(column = "qualifications", property = "qualifications", jdbcType = JdbcType.VARCHAR),
			@Result(column = "practicing", property = "practicing", jdbcType = JdbcType.VARCHAR),
			@Result(column = "createTime", property = "createtime", jdbcType = JdbcType.VARCHAR),
			@Result(column = "updateTime", property = "updatetime", jdbcType = JdbcType.VARCHAR) })
	List<EnterpriseAptitude> selectByExampleWithRowbounds(
			EnterpriseAptitudeExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_aptitude
	 * @mbggenerated  Wed Jan 13 12:15:38 CST 2016
	 */
	@SelectProvider(type = EnterpriseAptitudeSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "aptitudeId", property = "aptitudeid", jdbcType = JdbcType.TINYINT),
			@Result(column = "aptitudeRank", property = "aptituderank", jdbcType = JdbcType.TINYINT),
			@Result(column = "qualifications", property = "qualifications", jdbcType = JdbcType.VARCHAR),
			@Result(column = "practicing", property = "practicing", jdbcType = JdbcType.VARCHAR),
			@Result(column = "createTime", property = "createtime", jdbcType = JdbcType.VARCHAR),
			@Result(column = "updateTime", property = "updatetime", jdbcType = JdbcType.VARCHAR) })
	List<EnterpriseAptitude> selectByExample(EnterpriseAptitudeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_aptitude
	 * @mbggenerated  Wed Jan 13 12:15:38 CST 2016
	 */
	@Select({
			"select",
			"id, aptitudeId, aptitudeRank, qualifications, practicing, createTime, updateTime, ",
			"charge, technical, skills, jobRange", "from enterprise_aptitude",
			"where id = #{id,jdbcType=INTEGER}" })
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "aptitudeId", property = "aptitudeid", jdbcType = JdbcType.TINYINT),
			@Result(column = "aptitudeRank", property = "aptituderank", jdbcType = JdbcType.TINYINT),
			@Result(column = "qualifications", property = "qualifications", jdbcType = JdbcType.VARCHAR),
			@Result(column = "practicing", property = "practicing", jdbcType = JdbcType.VARCHAR),
			@Result(column = "createTime", property = "createtime", jdbcType = JdbcType.VARCHAR),
			@Result(column = "updateTime", property = "updatetime", jdbcType = JdbcType.VARCHAR),
			@Result(column = "charge", property = "charge", jdbcType = JdbcType.LONGVARCHAR),
			@Result(column = "technical", property = "technical", jdbcType = JdbcType.LONGVARCHAR),
			@Result(column = "skills", property = "skills", jdbcType = JdbcType.LONGVARCHAR),
			@Result(column = "jobRange", property = "jobrange", jdbcType = JdbcType.LONGVARCHAR) })
	EnterpriseAptitudeWithBLOBs selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_aptitude
	 * @mbggenerated  Wed Jan 13 12:15:38 CST 2016
	 */
	@UpdateProvider(type = EnterpriseAptitudeSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(
			@Param("record") EnterpriseAptitudeWithBLOBs record,
			@Param("example") EnterpriseAptitudeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_aptitude
	 * @mbggenerated  Wed Jan 13 12:15:38 CST 2016
	 */
	@UpdateProvider(type = EnterpriseAptitudeSqlProvider.class, method = "updateByExampleWithBLOBs")
	int updateByExampleWithBLOBs(
			@Param("record") EnterpriseAptitudeWithBLOBs record,
			@Param("example") EnterpriseAptitudeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_aptitude
	 * @mbggenerated  Wed Jan 13 12:15:38 CST 2016
	 */
	@UpdateProvider(type = EnterpriseAptitudeSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") EnterpriseAptitude record,
			@Param("example") EnterpriseAptitudeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_aptitude
	 * @mbggenerated  Wed Jan 13 12:15:38 CST 2016
	 */
	@UpdateProvider(type = EnterpriseAptitudeSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(EnterpriseAptitudeWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_aptitude
	 * @mbggenerated  Wed Jan 13 12:15:38 CST 2016
	 */
	@Update({ "update enterprise_aptitude",
			"set aptitudeId = #{aptitudeid,jdbcType=TINYINT},",
			"aptitudeRank = #{aptituderank,jdbcType=TINYINT},",
			"qualifications = #{qualifications,jdbcType=VARCHAR},",
			"practicing = #{practicing,jdbcType=VARCHAR},",
			"createTime = #{createtime,jdbcType=VARCHAR},",
			"updateTime = #{updatetime,jdbcType=VARCHAR},",
			"charge = #{charge,jdbcType=LONGVARCHAR},",
			"technical = #{technical,jdbcType=LONGVARCHAR},",
			"skills = #{skills,jdbcType=LONGVARCHAR},",
			"jobRange = #{jobrange,jdbcType=LONGVARCHAR}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKeyWithBLOBs(EnterpriseAptitudeWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_aptitude
	 * @mbggenerated  Wed Jan 13 12:15:38 CST 2016
	 */
	@Update({ "update enterprise_aptitude",
			"set aptitudeId = #{aptitudeid,jdbcType=TINYINT},",
			"aptitudeRank = #{aptituderank,jdbcType=TINYINT},",
			"qualifications = #{qualifications,jdbcType=VARCHAR},",
			"practicing = #{practicing,jdbcType=VARCHAR},",
			"createTime = #{createtime,jdbcType=VARCHAR},",
			"updateTime = #{updatetime,jdbcType=VARCHAR}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(EnterpriseAptitude record);
}