package com.ronyao.cca.db.dao;

import com.ronyao.cca.db.model.EnterpriseEquipment;
import com.ronyao.cca.db.model.EnterpriseEquipmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface EnterpriseEquipmentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_equipment
	 * @mbggenerated  Fri Dec 18 14:33:37 CST 2015
	 */
	@SelectProvider(type = EnterpriseEquipmentSqlProvider.class, method = "countByExample")
	int countByExample(EnterpriseEquipmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_equipment
	 * @mbggenerated  Fri Dec 18 14:33:37 CST 2015
	 */
	@DeleteProvider(type = EnterpriseEquipmentSqlProvider.class, method = "deleteByExample")
	int deleteByExample(EnterpriseEquipmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_equipment
	 * @mbggenerated  Fri Dec 18 14:33:37 CST 2015
	 */
	@Delete({ "delete from enterprise_equipment",
			"where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_equipment
	 * @mbggenerated  Fri Dec 18 14:33:37 CST 2015
	 */
	@Insert({
			"insert into enterprise_equipment (enterpriseId, bigEquipment, ",
			"smallEquipment, sum, ",
			"createTime, updateTime)",
			"values (#{enterpriseid,jdbcType=INTEGER}, #{bigequipment,jdbcType=INTEGER}, ",
			"#{smallequipment,jdbcType=INTEGER}, #{sum,jdbcType=INTEGER}, ",
			"#{createtime,jdbcType=VARCHAR}, #{updatetime,jdbcType=VARCHAR})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
	int insert(EnterpriseEquipment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_equipment
	 * @mbggenerated  Fri Dec 18 14:33:37 CST 2015
	 */
	@InsertProvider(type = EnterpriseEquipmentSqlProvider.class, method = "insertSelective")
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
	int insertSelective(EnterpriseEquipment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_equipment
	 * @mbggenerated  Fri Dec 18 14:33:37 CST 2015
	 */
	@SelectProvider(type = EnterpriseEquipmentSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "enterpriseId", property = "enterpriseid", jdbcType = JdbcType.INTEGER),
			@Result(column = "bigEquipment", property = "bigequipment", jdbcType = JdbcType.INTEGER),
			@Result(column = "smallEquipment", property = "smallequipment", jdbcType = JdbcType.INTEGER),
			@Result(column = "sum", property = "sum", jdbcType = JdbcType.INTEGER),
			@Result(column = "createTime", property = "createtime", jdbcType = JdbcType.VARCHAR),
			@Result(column = "updateTime", property = "updatetime", jdbcType = JdbcType.VARCHAR) })
	List<EnterpriseEquipment> selectByExampleWithRowbounds(
			EnterpriseEquipmentExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_equipment
	 * @mbggenerated  Fri Dec 18 14:33:37 CST 2015
	 */
	@SelectProvider(type = EnterpriseEquipmentSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "enterpriseId", property = "enterpriseid", jdbcType = JdbcType.INTEGER),
			@Result(column = "bigEquipment", property = "bigequipment", jdbcType = JdbcType.INTEGER),
			@Result(column = "smallEquipment", property = "smallequipment", jdbcType = JdbcType.INTEGER),
			@Result(column = "sum", property = "sum", jdbcType = JdbcType.INTEGER),
			@Result(column = "createTime", property = "createtime", jdbcType = JdbcType.VARCHAR),
			@Result(column = "updateTime", property = "updatetime", jdbcType = JdbcType.VARCHAR) })
	List<EnterpriseEquipment> selectByExample(EnterpriseEquipmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_equipment
	 * @mbggenerated  Fri Dec 18 14:33:37 CST 2015
	 */
	@Select({
			"select",
			"id, enterpriseId, bigEquipment, smallEquipment, sum, createTime, updateTime",
			"from enterprise_equipment", "where id = #{id,jdbcType=INTEGER}" })
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "enterpriseId", property = "enterpriseid", jdbcType = JdbcType.INTEGER),
			@Result(column = "bigEquipment", property = "bigequipment", jdbcType = JdbcType.INTEGER),
			@Result(column = "smallEquipment", property = "smallequipment", jdbcType = JdbcType.INTEGER),
			@Result(column = "sum", property = "sum", jdbcType = JdbcType.INTEGER),
			@Result(column = "createTime", property = "createtime", jdbcType = JdbcType.VARCHAR),
			@Result(column = "updateTime", property = "updatetime", jdbcType = JdbcType.VARCHAR) })
	EnterpriseEquipment selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_equipment
	 * @mbggenerated  Fri Dec 18 14:33:37 CST 2015
	 */
	@UpdateProvider(type = EnterpriseEquipmentSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") EnterpriseEquipment record,
			@Param("example") EnterpriseEquipmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_equipment
	 * @mbggenerated  Fri Dec 18 14:33:37 CST 2015
	 */
	@UpdateProvider(type = EnterpriseEquipmentSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") EnterpriseEquipment record,
			@Param("example") EnterpriseEquipmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_equipment
	 * @mbggenerated  Fri Dec 18 14:33:37 CST 2015
	 */
	@UpdateProvider(type = EnterpriseEquipmentSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(EnterpriseEquipment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_equipment
	 * @mbggenerated  Fri Dec 18 14:33:37 CST 2015
	 */
	@Update({ "update enterprise_equipment",
			"set enterpriseId = #{enterpriseid,jdbcType=INTEGER},",
			"bigEquipment = #{bigequipment,jdbcType=INTEGER},",
			"smallEquipment = #{smallequipment,jdbcType=INTEGER},",
			"sum = #{sum,jdbcType=INTEGER},",
			"createTime = #{createtime,jdbcType=VARCHAR},",
			"updateTime = #{updatetime,jdbcType=VARCHAR}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(EnterpriseEquipment record);
}