package com.ronyao.cca.db.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.ronyao.cca.db.model.EnterpriseAssess;
import com.ronyao.cca.db.model.EnterpriseAssessExample.Criteria;
import com.ronyao.cca.db.model.EnterpriseAssessExample.Criterion;
import com.ronyao.cca.db.model.EnterpriseAssessExample;
import java.util.List;
import java.util.Map;

public class EnterpriseAssessSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_assess
	 * @mbggenerated  Tue Dec 22 14:07:13 CST 2015
	 */
	public String countByExample(EnterpriseAssessExample example) {
		BEGIN();
		SELECT("count(*)");
		FROM("enterprise_assess");
		applyWhere(example, false);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_assess
	 * @mbggenerated  Tue Dec 22 14:07:13 CST 2015
	 */
	public String deleteByExample(EnterpriseAssessExample example) {
		BEGIN();
		DELETE_FROM("enterprise_assess");
		applyWhere(example, false);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_assess
	 * @mbggenerated  Tue Dec 22 14:07:13 CST 2015
	 */
	public String insertSelective(EnterpriseAssess record) {
		BEGIN();
		INSERT_INTO("enterprise_assess");
		if (record.getCategory() != null) {
			VALUES("category", "#{category,jdbcType=VARCHAR}");
		}
		if (record.getStandard() != null) {
			VALUES("standard", "#{standard,jdbcType=VARCHAR}");
		}
		if (record.getProjectnumstart() != null) {
			VALUES("projectNumStart", "#{projectnumstart,jdbcType=INTEGER}");
		}
		if (record.getProjectnumend() != null) {
			VALUES("projectNumEnd", "#{projectnumend,jdbcType=INTEGER}");
		}
		if (record.getOutputstart() != null) {
			VALUES("outputStart", "#{outputstart,jdbcType=DECIMAL}");
		}
		if (record.getOutputend() != null) {
			VALUES("outputEnd", "#{outputend,jdbcType=DECIMAL}");
		}
		if (record.getCreatetime() != null) {
			VALUES("createTime", "#{createtime,jdbcType=VARCHAR}");
		}
		if (record.getUpdatetime() != null) {
			VALUES("updateTime", "#{updatetime,jdbcType=VARCHAR}");
		}
		if (record.getEnterprise() != null) {
			VALUES("enterprise", "#{enterprise,jdbcType=LONGVARCHAR}");
		}
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_assess
	 * @mbggenerated  Tue Dec 22 14:07:13 CST 2015
	 */
	public String selectByExampleWithBLOBs(EnterpriseAssessExample example) {
		BEGIN();
		if (example != null && example.isDistinct()) {
			SELECT_DISTINCT("id");
		} else {
			SELECT("id");
		}
		SELECT("category");
		SELECT("standard");
		SELECT("projectNumStart");
		SELECT("projectNumEnd");
		SELECT("outputStart");
		SELECT("outputEnd");
		SELECT("createTime");
		SELECT("updateTime");
		SELECT("enterprise");
		FROM("enterprise_assess");
		applyWhere(example, false);
		if (example != null && example.getOrderByClause() != null) {
			ORDER_BY(example.getOrderByClause());
		}
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_assess
	 * @mbggenerated  Tue Dec 22 14:07:13 CST 2015
	 */
	public String selectByExample(EnterpriseAssessExample example) {
		BEGIN();
		if (example != null && example.isDistinct()) {
			SELECT_DISTINCT("id");
		} else {
			SELECT("id");
		}
		SELECT("category");
		SELECT("standard");
		SELECT("projectNumStart");
		SELECT("projectNumEnd");
		SELECT("outputStart");
		SELECT("outputEnd");
		SELECT("createTime");
		SELECT("updateTime");
		FROM("enterprise_assess");
		applyWhere(example, false);
		if (example != null && example.getOrderByClause() != null) {
			ORDER_BY(example.getOrderByClause());
		}
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_assess
	 * @mbggenerated  Tue Dec 22 14:07:13 CST 2015
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		EnterpriseAssess record = (EnterpriseAssess) parameter.get("record");
		EnterpriseAssessExample example = (EnterpriseAssessExample) parameter
				.get("example");
		BEGIN();
		UPDATE("enterprise_assess");
		if (record.getId() != null) {
			SET("id = #{record.id,jdbcType=INTEGER}");
		}
		if (record.getCategory() != null) {
			SET("category = #{record.category,jdbcType=VARCHAR}");
		}
		if (record.getStandard() != null) {
			SET("standard = #{record.standard,jdbcType=VARCHAR}");
		}
		if (record.getProjectnumstart() != null) {
			SET("projectNumStart = #{record.projectnumstart,jdbcType=INTEGER}");
		}
		if (record.getProjectnumend() != null) {
			SET("projectNumEnd = #{record.projectnumend,jdbcType=INTEGER}");
		}
		if (record.getOutputstart() != null) {
			SET("outputStart = #{record.outputstart,jdbcType=DECIMAL}");
		}
		if (record.getOutputend() != null) {
			SET("outputEnd = #{record.outputend,jdbcType=DECIMAL}");
		}
		if (record.getCreatetime() != null) {
			SET("createTime = #{record.createtime,jdbcType=VARCHAR}");
		}
		if (record.getUpdatetime() != null) {
			SET("updateTime = #{record.updatetime,jdbcType=VARCHAR}");
		}
		if (record.getEnterprise() != null) {
			SET("enterprise = #{record.enterprise,jdbcType=LONGVARCHAR}");
		}
		applyWhere(example, true);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_assess
	 * @mbggenerated  Tue Dec 22 14:07:13 CST 2015
	 */
	public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
		BEGIN();
		UPDATE("enterprise_assess");
		SET("id = #{record.id,jdbcType=INTEGER}");
		SET("category = #{record.category,jdbcType=VARCHAR}");
		SET("standard = #{record.standard,jdbcType=VARCHAR}");
		SET("projectNumStart = #{record.projectnumstart,jdbcType=INTEGER}");
		SET("projectNumEnd = #{record.projectnumend,jdbcType=INTEGER}");
		SET("outputStart = #{record.outputstart,jdbcType=DECIMAL}");
		SET("outputEnd = #{record.outputend,jdbcType=DECIMAL}");
		SET("createTime = #{record.createtime,jdbcType=VARCHAR}");
		SET("updateTime = #{record.updatetime,jdbcType=VARCHAR}");
		SET("enterprise = #{record.enterprise,jdbcType=LONGVARCHAR}");
		EnterpriseAssessExample example = (EnterpriseAssessExample) parameter
				.get("example");
		applyWhere(example, true);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_assess
	 * @mbggenerated  Tue Dec 22 14:07:13 CST 2015
	 */
	public String updateByExample(Map<String, Object> parameter) {
		BEGIN();
		UPDATE("enterprise_assess");
		SET("id = #{record.id,jdbcType=INTEGER}");
		SET("category = #{record.category,jdbcType=VARCHAR}");
		SET("standard = #{record.standard,jdbcType=VARCHAR}");
		SET("projectNumStart = #{record.projectnumstart,jdbcType=INTEGER}");
		SET("projectNumEnd = #{record.projectnumend,jdbcType=INTEGER}");
		SET("outputStart = #{record.outputstart,jdbcType=DECIMAL}");
		SET("outputEnd = #{record.outputend,jdbcType=DECIMAL}");
		SET("createTime = #{record.createtime,jdbcType=VARCHAR}");
		SET("updateTime = #{record.updatetime,jdbcType=VARCHAR}");
		EnterpriseAssessExample example = (EnterpriseAssessExample) parameter
				.get("example");
		applyWhere(example, true);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_assess
	 * @mbggenerated  Tue Dec 22 14:07:13 CST 2015
	 */
	public String updateByPrimaryKeySelective(EnterpriseAssess record) {
		BEGIN();
		UPDATE("enterprise_assess");
		if (record.getCategory() != null) {
			SET("category = #{category,jdbcType=VARCHAR}");
		}
		if (record.getStandard() != null) {
			SET("standard = #{standard,jdbcType=VARCHAR}");
		}
		if (record.getProjectnumstart() != null) {
			SET("projectNumStart = #{projectnumstart,jdbcType=INTEGER}");
		}
		if (record.getProjectnumend() != null) {
			SET("projectNumEnd = #{projectnumend,jdbcType=INTEGER}");
		}
		if (record.getOutputstart() != null) {
			SET("outputStart = #{outputstart,jdbcType=DECIMAL}");
		}
		if (record.getOutputend() != null) {
			SET("outputEnd = #{outputend,jdbcType=DECIMAL}");
		}
		if (record.getCreatetime() != null) {
			SET("createTime = #{createtime,jdbcType=VARCHAR}");
		}
		if (record.getUpdatetime() != null) {
			SET("updateTime = #{updatetime,jdbcType=VARCHAR}");
		}
		if (record.getEnterprise() != null) {
			SET("enterprise = #{enterprise,jdbcType=LONGVARCHAR}");
		}
		WHERE("id = #{id,jdbcType=INTEGER}");
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_assess
	 * @mbggenerated  Tue Dec 22 14:07:13 CST 2015
	 */
	protected void applyWhere(EnterpriseAssessExample example,
			boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1,
									criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th,
									criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2,
									criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th,
									criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j,
										k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			WHERE(sb.toString());
		}
	}
}