package com.ronyao.cca.db.dao;

import com.ronyao.cca.db.model.EnterprisePerStandard;
import com.ronyao.cca.db.model.EnterprisePerStandardExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface EnterprisePerStandardMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_per_standard
	 * @mbggenerated  Thu Dec 10 14:41:03 CST 2015
	 */
	@SelectProvider(type = EnterprisePerStandardSqlProvider.class, method = "countByExample")
	int countByExample(EnterprisePerStandardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_per_standard
	 * @mbggenerated  Thu Dec 10 14:41:03 CST 2015
	 */
	@DeleteProvider(type = EnterprisePerStandardSqlProvider.class, method = "deleteByExample")
	int deleteByExample(EnterprisePerStandardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_per_standard
	 * @mbggenerated  Thu Dec 10 14:41:03 CST 2015
	 */
	@Delete({ "delete from enterprise_per_standard",
			"where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_per_standard
	 * @mbggenerated  Thu Dec 10 14:41:03 CST 2015
	 */
	@Insert({
			"insert into enterprise_per_standard (postClassifyId, holderRequire, ",
			"lineFlatNum, lineMountainNum, ",
			"powerNum, job, remark, ",
			"createTime, updateTime)",
			"values (#{postclassifyid,jdbcType=TINYINT}, #{holderrequire,jdbcType=VARCHAR}, ",
			"#{lineflatnum,jdbcType=TINYINT}, #{linemountainnum,jdbcType=TINYINT}, ",
			"#{powernum,jdbcType=TINYINT}, #{job,jdbcType=TINYINT}, #{remark,jdbcType=VARCHAR}, ",
			"#{createtime,jdbcType=VARCHAR}, #{updatetime,jdbcType=VARCHAR})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
	int insert(EnterprisePerStandard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_per_standard
	 * @mbggenerated  Thu Dec 10 14:41:03 CST 2015
	 */
	@InsertProvider(type = EnterprisePerStandardSqlProvider.class, method = "insertSelective")
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
	int insertSelective(EnterprisePerStandard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_per_standard
	 * @mbggenerated  Thu Dec 10 14:41:03 CST 2015
	 */
	@SelectProvider(type = EnterprisePerStandardSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "postClassifyId", property = "postclassifyid", jdbcType = JdbcType.TINYINT),
			@Result(column = "holderRequire", property = "holderrequire", jdbcType = JdbcType.VARCHAR),
			@Result(column = "lineFlatNum", property = "lineflatnum", jdbcType = JdbcType.TINYINT),
			@Result(column = "lineMountainNum", property = "linemountainnum", jdbcType = JdbcType.TINYINT),
			@Result(column = "powerNum", property = "powernum", jdbcType = JdbcType.TINYINT),
			@Result(column = "job", property = "job", jdbcType = JdbcType.TINYINT),
			@Result(column = "remark", property = "remark", jdbcType = JdbcType.VARCHAR),
			@Result(column = "createTime", property = "createtime", jdbcType = JdbcType.VARCHAR),
			@Result(column = "updateTime", property = "updatetime", jdbcType = JdbcType.VARCHAR) })
	List<EnterprisePerStandard> selectByExampleWithRowbounds(
			EnterprisePerStandardExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_per_standard
	 * @mbggenerated  Thu Dec 10 14:41:03 CST 2015
	 */
	@SelectProvider(type = EnterprisePerStandardSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "postClassifyId", property = "postclassifyid", jdbcType = JdbcType.TINYINT),
			@Result(column = "holderRequire", property = "holderrequire", jdbcType = JdbcType.VARCHAR),
			@Result(column = "lineFlatNum", property = "lineflatnum", jdbcType = JdbcType.TINYINT),
			@Result(column = "lineMountainNum", property = "linemountainnum", jdbcType = JdbcType.TINYINT),
			@Result(column = "powerNum", property = "powernum", jdbcType = JdbcType.TINYINT),
			@Result(column = "job", property = "job", jdbcType = JdbcType.TINYINT),
			@Result(column = "remark", property = "remark", jdbcType = JdbcType.VARCHAR),
			@Result(column = "createTime", property = "createtime", jdbcType = JdbcType.VARCHAR),
			@Result(column = "updateTime", property = "updatetime", jdbcType = JdbcType.VARCHAR) })
	List<EnterprisePerStandard> selectByExample(
			EnterprisePerStandardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_per_standard
	 * @mbggenerated  Thu Dec 10 14:41:03 CST 2015
	 */
	@Select({
			"select",
			"id, postClassifyId, holderRequire, lineFlatNum, lineMountainNum, powerNum, job, ",
			"remark, createTime, updateTime", "from enterprise_per_standard",
			"where id = #{id,jdbcType=INTEGER}" })
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "postClassifyId", property = "postclassifyid", jdbcType = JdbcType.TINYINT),
			@Result(column = "holderRequire", property = "holderrequire", jdbcType = JdbcType.VARCHAR),
			@Result(column = "lineFlatNum", property = "lineflatnum", jdbcType = JdbcType.TINYINT),
			@Result(column = "lineMountainNum", property = "linemountainnum", jdbcType = JdbcType.TINYINT),
			@Result(column = "powerNum", property = "powernum", jdbcType = JdbcType.TINYINT),
			@Result(column = "job", property = "job", jdbcType = JdbcType.TINYINT),
			@Result(column = "remark", property = "remark", jdbcType = JdbcType.VARCHAR),
			@Result(column = "createTime", property = "createtime", jdbcType = JdbcType.VARCHAR),
			@Result(column = "updateTime", property = "updatetime", jdbcType = JdbcType.VARCHAR) })
	EnterprisePerStandard selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_per_standard
	 * @mbggenerated  Thu Dec 10 14:41:03 CST 2015
	 */
	@UpdateProvider(type = EnterprisePerStandardSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") EnterprisePerStandard record,
			@Param("example") EnterprisePerStandardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_per_standard
	 * @mbggenerated  Thu Dec 10 14:41:03 CST 2015
	 */
	@UpdateProvider(type = EnterprisePerStandardSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") EnterprisePerStandard record,
			@Param("example") EnterprisePerStandardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_per_standard
	 * @mbggenerated  Thu Dec 10 14:41:03 CST 2015
	 */
	@UpdateProvider(type = EnterprisePerStandardSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(EnterprisePerStandard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_per_standard
	 * @mbggenerated  Thu Dec 10 14:41:03 CST 2015
	 */
	@Update({ "update enterprise_per_standard",
			"set postClassifyId = #{postclassifyid,jdbcType=TINYINT},",
			"holderRequire = #{holderrequire,jdbcType=VARCHAR},",
			"lineFlatNum = #{lineflatnum,jdbcType=TINYINT},",
			"lineMountainNum = #{linemountainnum,jdbcType=TINYINT},",
			"powerNum = #{powernum,jdbcType=TINYINT},",
			"job = #{job,jdbcType=TINYINT},",
			"remark = #{remark,jdbcType=VARCHAR},",
			"createTime = #{createtime,jdbcType=VARCHAR},",
			"updateTime = #{updatetime,jdbcType=VARCHAR}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(EnterprisePerStandard record);
}