package com.ronyao.cca.db.dao;

import com.ronyao.cca.db.model.ProjectBuild;
import com.ronyao.cca.db.model.ProjectBuildExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface ProjectBuildMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_build
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	@SelectProvider(type = ProjectBuildSqlProvider.class, method = "countByExample")
	int countByExample(ProjectBuildExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_build
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	@DeleteProvider(type = ProjectBuildSqlProvider.class, method = "deleteByExample")
	int deleteByExample(ProjectBuildExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_build
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	@Delete({ "delete from project_build", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_build
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	@Insert({
			"insert into project_build (supervisorUnit, enterpriseId, ",
			"year, classify, ",
			"line110kv, line220kv, ",
			"line500kv, power110kv, ",
			"power220kv, power500kv, ",
			"createTime, updateTime)",
			"values (#{supervisorunit,jdbcType=VARCHAR}, #{enterpriseid,jdbcType=INTEGER}, ",
			"#{year,jdbcType=INTEGER}, #{classify,jdbcType=INTEGER}, ",
			"#{line110kv,jdbcType=INTEGER}, #{line220kv,jdbcType=INTEGER}, ",
			"#{line500kv,jdbcType=INTEGER}, #{power110kv,jdbcType=INTEGER}, ",
			"#{power220kv,jdbcType=INTEGER}, #{power500kv,jdbcType=INTEGER}, ",
			"#{createtime,jdbcType=VARCHAR}, #{updatetime,jdbcType=VARCHAR})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
	int insert(ProjectBuild record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_build
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	@InsertProvider(type = ProjectBuildSqlProvider.class, method = "insertSelective")
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
	int insertSelective(ProjectBuild record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_build
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	@SelectProvider(type = ProjectBuildSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "supervisorUnit", property = "supervisorunit", jdbcType = JdbcType.VARCHAR),
			@Result(column = "enterpriseId", property = "enterpriseid", jdbcType = JdbcType.INTEGER),
			@Result(column = "year", property = "year", jdbcType = JdbcType.INTEGER),
			@Result(column = "classify", property = "classify", jdbcType = JdbcType.INTEGER),
			@Result(column = "line110kv", property = "line110kv", jdbcType = JdbcType.INTEGER),
			@Result(column = "line220kv", property = "line220kv", jdbcType = JdbcType.INTEGER),
			@Result(column = "line500kv", property = "line500kv", jdbcType = JdbcType.INTEGER),
			@Result(column = "power110kv", property = "power110kv", jdbcType = JdbcType.INTEGER),
			@Result(column = "power220kv", property = "power220kv", jdbcType = JdbcType.INTEGER),
			@Result(column = "power500kv", property = "power500kv", jdbcType = JdbcType.INTEGER),
			@Result(column = "createTime", property = "createtime", jdbcType = JdbcType.VARCHAR),
			@Result(column = "updateTime", property = "updatetime", jdbcType = JdbcType.VARCHAR) })
	List<ProjectBuild> selectByExampleWithRowbounds(
			ProjectBuildExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_build
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	@SelectProvider(type = ProjectBuildSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "supervisorUnit", property = "supervisorunit", jdbcType = JdbcType.VARCHAR),
			@Result(column = "enterpriseId", property = "enterpriseid", jdbcType = JdbcType.INTEGER),
			@Result(column = "year", property = "year", jdbcType = JdbcType.INTEGER),
			@Result(column = "classify", property = "classify", jdbcType = JdbcType.INTEGER),
			@Result(column = "line110kv", property = "line110kv", jdbcType = JdbcType.INTEGER),
			@Result(column = "line220kv", property = "line220kv", jdbcType = JdbcType.INTEGER),
			@Result(column = "line500kv", property = "line500kv", jdbcType = JdbcType.INTEGER),
			@Result(column = "power110kv", property = "power110kv", jdbcType = JdbcType.INTEGER),
			@Result(column = "power220kv", property = "power220kv", jdbcType = JdbcType.INTEGER),
			@Result(column = "power500kv", property = "power500kv", jdbcType = JdbcType.INTEGER),
			@Result(column = "createTime", property = "createtime", jdbcType = JdbcType.VARCHAR),
			@Result(column = "updateTime", property = "updatetime", jdbcType = JdbcType.VARCHAR) })
	List<ProjectBuild> selectByExample(ProjectBuildExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_build
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	@Select({
			"select",
			"id, supervisorUnit, enterpriseId, year, classify, line110kv, line220kv, line500kv, ",
			"power110kv, power220kv, power500kv, createTime, updateTime",
			"from project_build", "where id = #{id,jdbcType=INTEGER}" })
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "supervisorUnit", property = "supervisorunit", jdbcType = JdbcType.VARCHAR),
			@Result(column = "enterpriseId", property = "enterpriseid", jdbcType = JdbcType.INTEGER),
			@Result(column = "year", property = "year", jdbcType = JdbcType.INTEGER),
			@Result(column = "classify", property = "classify", jdbcType = JdbcType.INTEGER),
			@Result(column = "line110kv", property = "line110kv", jdbcType = JdbcType.INTEGER),
			@Result(column = "line220kv", property = "line220kv", jdbcType = JdbcType.INTEGER),
			@Result(column = "line500kv", property = "line500kv", jdbcType = JdbcType.INTEGER),
			@Result(column = "power110kv", property = "power110kv", jdbcType = JdbcType.INTEGER),
			@Result(column = "power220kv", property = "power220kv", jdbcType = JdbcType.INTEGER),
			@Result(column = "power500kv", property = "power500kv", jdbcType = JdbcType.INTEGER),
			@Result(column = "createTime", property = "createtime", jdbcType = JdbcType.VARCHAR),
			@Result(column = "updateTime", property = "updatetime", jdbcType = JdbcType.VARCHAR) })
	ProjectBuild selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_build
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	@UpdateProvider(type = ProjectBuildSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") ProjectBuild record,
			@Param("example") ProjectBuildExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_build
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	@UpdateProvider(type = ProjectBuildSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") ProjectBuild record,
			@Param("example") ProjectBuildExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_build
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	@UpdateProvider(type = ProjectBuildSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(ProjectBuild record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table project_build
	 * @mbggenerated  Mon Jan 04 10:04:47 CST 2016
	 */
	@Update({ "update project_build",
			"set supervisorUnit = #{supervisorunit,jdbcType=VARCHAR},",
			"enterpriseId = #{enterpriseid,jdbcType=INTEGER},",
			"year = #{year,jdbcType=INTEGER},",
			"classify = #{classify,jdbcType=INTEGER},",
			"line110kv = #{line110kv,jdbcType=INTEGER},",
			"line220kv = #{line220kv,jdbcType=INTEGER},",
			"line500kv = #{line500kv,jdbcType=INTEGER},",
			"power110kv = #{power110kv,jdbcType=INTEGER},",
			"power220kv = #{power220kv,jdbcType=INTEGER},",
			"power500kv = #{power500kv,jdbcType=INTEGER},",
			"createTime = #{createtime,jdbcType=VARCHAR},",
			"updateTime = #{updatetime,jdbcType=VARCHAR}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(ProjectBuild record);
}