package com.ronyao.cca.db.dao;

import com.ronyao.cca.db.model.RolePermissionLink;
import com.ronyao.cca.db.model.RolePermissionLinkExample;
import com.ronyao.cca.db.model.RolePermissionLinkKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface RolePermissionLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_link
     *
     * @mbggenerated Wed Jan 13 12:15:38 CST 2016
     */
    @SelectProvider(type=RolePermissionLinkSqlProvider.class, method="countByExample")
    int countByExample(RolePermissionLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_link
     *
     * @mbggenerated Wed Jan 13 12:15:38 CST 2016
     */
    @DeleteProvider(type=RolePermissionLinkSqlProvider.class, method="deleteByExample")
    int deleteByExample(RolePermissionLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_link
     *
     * @mbggenerated Wed Jan 13 12:15:38 CST 2016
     */
    @Delete({
        "delete from role_permission_link",
        "where roleId = #{roleid,jdbcType=INTEGER}",
          "and permissionId = #{permissionid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(RolePermissionLinkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_link
     *
     * @mbggenerated Wed Jan 13 12:15:38 CST 2016
     */
    @Insert({
        "insert into role_permission_link (roleId, permissionId, ",
        "status, createTime, ",
        "updateTime)",
        "values (#{roleid,jdbcType=INTEGER}, #{permissionid,jdbcType=INTEGER}, ",
        "#{status,jdbcType=TINYINT}, #{createtime,jdbcType=VARCHAR}, ",
        "#{updatetime,jdbcType=VARCHAR})"
    })
    int insert(RolePermissionLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_link
     *
     * @mbggenerated Wed Jan 13 12:15:38 CST 2016
     */
    @InsertProvider(type=RolePermissionLinkSqlProvider.class, method="insertSelective")
    int insertSelective(RolePermissionLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_link
     *
     * @mbggenerated Wed Jan 13 12:15:38 CST 2016
     */
    @SelectProvider(type=RolePermissionLinkSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="roleId", property="roleid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="permissionId", property="permissionid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="createTime", property="createtime", jdbcType=JdbcType.VARCHAR),
        @Result(column="updateTime", property="updatetime", jdbcType=JdbcType.VARCHAR)
    })
    List<RolePermissionLink> selectByExampleWithRowbounds(RolePermissionLinkExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_link
     *
     * @mbggenerated Wed Jan 13 12:15:38 CST 2016
     */
    @SelectProvider(type=RolePermissionLinkSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="roleId", property="roleid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="permissionId", property="permissionid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="createTime", property="createtime", jdbcType=JdbcType.VARCHAR),
        @Result(column="updateTime", property="updatetime", jdbcType=JdbcType.VARCHAR)
    })
    List<RolePermissionLink> selectByExample(RolePermissionLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_link
     *
     * @mbggenerated Wed Jan 13 12:15:38 CST 2016
     */
    @Select({
        "select",
        "roleId, permissionId, status, createTime, updateTime",
        "from role_permission_link",
        "where roleId = #{roleid,jdbcType=INTEGER}",
          "and permissionId = #{permissionid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="roleId", property="roleid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="permissionId", property="permissionid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="createTime", property="createtime", jdbcType=JdbcType.VARCHAR),
        @Result(column="updateTime", property="updatetime", jdbcType=JdbcType.VARCHAR)
    })
    RolePermissionLink selectByPrimaryKey(RolePermissionLinkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_link
     *
     * @mbggenerated Wed Jan 13 12:15:38 CST 2016
     */
    @UpdateProvider(type=RolePermissionLinkSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") RolePermissionLink record, @Param("example") RolePermissionLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_link
     *
     * @mbggenerated Wed Jan 13 12:15:38 CST 2016
     */
    @UpdateProvider(type=RolePermissionLinkSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") RolePermissionLink record, @Param("example") RolePermissionLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_link
     *
     * @mbggenerated Wed Jan 13 12:15:38 CST 2016
     */
    @UpdateProvider(type=RolePermissionLinkSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(RolePermissionLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_link
     *
     * @mbggenerated Wed Jan 13 12:15:38 CST 2016
     */
    @Update({
        "update role_permission_link",
        "set status = #{status,jdbcType=TINYINT},",
          "createTime = #{createtime,jdbcType=VARCHAR},",
          "updateTime = #{updatetime,jdbcType=VARCHAR}",
        "where roleId = #{roleid,jdbcType=INTEGER}",
          "and permissionId = #{permissionid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(RolePermissionLink record);
}